---
x-server-env: &server-env
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
  DATABASE_ENGINE: ${DATABASE_ENGINE}
  DATABASE_HOST: postgres
  DATABASE_PORT: ${POSTGRES_PORT}
  DATABASE_NAME: ${POSTGRES_DB}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}
  CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
  ALLOWED_HOSTS: ${ALLOWED_HOSTS}
  REST_FRAMEWORK_PAGE_SIZE: ${REST_FRAMEWORK_PAGE_SIZE}

services:

  server:
    image: stangirard/osat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      <<: *server-env
    volumes:
    - server-data:/opt/app/data
    - ./shared/logs/server:/opt/app/logs
    container_name: ${NAMESPACE}-server
    ports:
      - "8000:8000"
    command: ["django"]
    depends_on:
    - worker
    - beats
    - postgres
    - dashboard
    labels:
    - "org.label-schema.group=webservice"
    networks:
    - internal
    restart: unless-stopped

  worker:
    image: stangirard/osat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      <<: *server-env
    volumes:
    - server-data:/opt/app/data
    - ./shared/logs/server:/opt/app/logs
    container_name: ${NAMESPACE}-worker
    depends_on:
    - redis
    labels:
    - "org.label-schema.group=queue"
    networks:
    - internal
    command: ["worker"]
    restart: unless-stopped

  beats:
    image: stangirard/osat-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      <<: *server-env
    volumes:
    - server-data:/opt/app/data
    - ./shared/logs/server:/opt/app/logs
    container_name: ${NAMESPACE}-beats
    depends_on:
    - redis
    labels:
    - "org.label-schema.group=queue"
    networks:
    - internal
    command: ["beat"]
    restart: unless-stopped

  dashboard:
    image: stangirard/osat-dashboard
    container_name: ${NAMESPACE}-dashboard
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
    - ./admin/Caddyfile:/etc/caddy/Caddyfile:rw
    expose:
    - 80
    ports:
    - 3000:80
    networks:
    - internal
    labels:
    - "org.label-schema.group=front"
    restart: unless-stopped

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${NAMESPACE}-postgres
    networks:
    - internal
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    labels:
    - "org.label-schema.group=storage"
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: ${NAMESPACE}-redis
    hostname: redis
    networks:
    - internal
    volumes:
    - redis-data:/data
    labels:
    - "org.label-schema.group=storage"
    command:
    - "redis-server"
    - "--maxmemory ${REDIS_MEMORY_MAX}"
    - "--maxmemory-policy allkeys-lru"
    restart: unless-stopped

networks:
  internal:
    driver: bridge

volumes:
  # server data
  server-data:
  # PostreSQL
  postgres-data:
  # Redis
  redis-data:
