ARG NODE_VERSION=${NODE_VERSION:-"20"}

FROM node:${NODE_VERSION}-alpine

# Import project's dependencies
WORKDIR /app
COPY package.json ./

RUN yarn install --network-timeout 1000000000

# Copy source files
COPY . .

# Container configuration
EXPOSE 3000

CMD ["yarn", "start"]